export const CURRENT_LOCATION = 'CURRENT_LOCATION';
export const SUCCESS_LOCATION = 'SUCCESS_LOCATION';
export const FAILED_LOCATION = 'FAILED_LOCATION';
export const MARK_SUCCESS = 'MARK_SUCCESS';
export const SUCCESS_GEOREVERSE = 'SUCCESS_GEOREVERSE';

