export const SESSION_RESTORING = 'SESSION_RESTORING';
export const SESSION_LOADING = 'SESSION_LOADING';
export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SESSION_ERROR = 'SESSION_ERROR';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
export const MATCHES_SUCCESS = 'MATCHES_SUCCESS';
export const LASTMESSAGES_SUCCESS = 'LASTMESSAGES_SUCCESS';
export const WIZARD_SUCCESS = 'WIZARD_SUCCESS';
export const USERDATA_SUCCESS = 'USERDATA_SUCCESS';

